"""Shared output constants for loop tests."""

HEADER_EVEN_ODD = "-------------------------------- Numeros pares e impares --------------------------------"
HEADER_AVERAGE_GRADES = "-------------------------------- Media de notas --------------------------------"
HEADER_PRIME_NUMBER = "-------------------------------- Numero primo --------------------------------"
HEADER_INTEGERS = "-------------------------------- Numeros inteiros --------------------------------"
HEADER_PRIME_NUMBERS = "-------------------------------- Numeros primos --------------------------------"
HEADER_SERIES_TENS = "-------------------------------- Serie de 10 em 10 --------------------------------"
HEADER_SERIES_FIFTEENS = "-------------------------------- Serie de 15 em 10 --------------------------------"
HEADER_REQUEST_NUMBER_RANGE = "-------------------------------- Solicitar numero entre 1 e 100 --------------------------------"
HEADER_COUNT_DIVISORS = "-------------------------------- Contar divisores --------------------------------"
HEADER_OUTPUT_NUMBERS = "-------------------------------- Output de numeros --------------------------------"
HEADER_OPERATIONS_NUMBERS = "-------------------------------- Operacoes com numeros --------------------------------"
HEADER_TABLE = "-------------------------------- Tabuada --------------------------------"
HEADER_TABLE_1_TO_100 = "-------------------------------- Tabuada de 1 a 100 --------------------------------"
HEADER_ASCII = "-------------------------------- Codigo ASCII --------------------------------"
HEADER_EVEN_NUMBERS_AVERAGE = "-------------------------------- Media de numeros pares --------------------------------"
HEADER_MULTIPLES_5_NOT_3 = "-------------------------------- Multiplos de 5 mas nao multiplos de 3 --------------------------------"
HEADER_PERFECT_NUMBERS = "-------------------------------- Numeros perfeitos --------------------------------"
HEADER_FIBONACCI_SERIES = "-------------------------------- Serie de Fibonacci --------------------------------"
HEADER_NUMBER_ANALYSIS = "-------------------------------- Programa de analise de numeros --------------------------------"
HEADER_SIMPLE_CALCULATOR = "-------------------------------- Calculadora simples --------------------------------"
HEADER_CLIENT_DATABASE = "-------------------------------- Base de dados de clientes --------------------------------"
EXIT_MESSAGE = "A sair do programa."
