"""Shared output constants for loop tests."""

HEADER_EVEN_ODD = "-------------------------------- Numeros pares e impares --------------------------------"
HEADER_INTEGERS = "-------------------------------- Numeros inteiros --------------------------------"
HEADER_SERIES_TENS = "-------------------------------- Serie de 10 em 10 --------------------------------"
HEADER_SERIES_FIFTEENS = "-------------------------------- Serie de 15 em 10 --------------------------------"
HEADER_TABLE = "-------------------------------- Tabuada --------------------------------"
HEADER_TABLE_1_TO_100 = "-------------------------------- Tabuada de 1 a 100 --------------------------------"
HEADER_ASCII = "-------------------------------- Codigo ASCII --------------------------------"
EXIT_MESSAGE = "A sair do programa."
